name: Build & Release
run-name: Build & Release of Logsea v${{ inputs.version }} triggered manually by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string
      latest:
        description: Mark as latest
        type: boolean
        default: false

env:
  IMAGE_NAME: logsea

jobs:
  release:
    name: Build & Release Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        tags: dusanlazic/logsea:${{ inputs.version }}${{ inputs.latest && ',dusanlazic/logsea:latest' || '' }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VERSION=${{ inputs.version }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.version }}
        name: v${{ inputs.version }}
        draft: false
        prerelease: false
        make_latest: ${{ github.event.inputs.latest }}
        token: ${{ secrets.GITHUB_TOKEN }}
